#!/usr/bin/bash

cp -a /home/mike/wdir/Prime_Squares /home/mike/Dropbox/Prime_Squares.new
mv /home/mike/Dropbox/Prime_Squares /home/mike/Dropbox/Prime_Squares.old
mv /home/mike/Dropbox/Prime_Squares.new /home/mike/Dropbox/Prime_Squares
ls -l  /home/mike/Dropbox

