#!/usr/bin/bash

cp -a /home/mike/wdir/PrimeSquares /home/mike/Dropbox/PrimeSquares.new
mv /home/mike/Dropbox/PrimeSquares /home/mike/Dropbox/PrimeSquares.old
mv /home/mike/Dropbox/PrimeSquares.new /home/mike/Dropbox/PrimeSquares
ls -l  /home/mike/Dropbox

